### ISSUE TITLE
Nodeserver Nodes Label

### ISSUE THREAD

**Issue by macjeff** [simplextech/udi-poly-inventory#1]
The label says Nodesevers but really that is Node Server Nodes correct?  I am running 19 node servers right now and have a total of 253 nodes from them.

So maybe you could change the label or add a nodeserver count and a nodeserver nodes.

<img width="1275" alt="Screen Shot 2020-02-25 at 6 53 22 PM" src="https://user-images.githubusercontent.com/20373758/75298618-ff9dd700-5800-11ea-9aab-e28ad1dfd56d.png">

**Comment by simplextech** [comment]
- Changed to be more specific of "NodeServer Nodes"
