### ISSUE TITLE
Instructions Correct for shortpoll and longpoll?

### ISSUE THREAD

**Issue by SteveSBE** [simplextech/udi-poly-inventory#4]
The [ReadMe](https://github.com/simplextech/udi-poly-inventory/blob/master/README.md#isy-inventory) says that the default long poll should be 4 minutes and the shortpoll 24 hours. Is this correct?  Thanks, Steve

**Comment by simplextech** [comment]
Longpoll is technically not used for anything and could be removed or I could swap them.  But yes it's correct.
